palette = 'github-dark'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[palettes.github-dark]
purple = "#BC8CFF"
orange = "#D29922"
yellow = "#E3B341"
blue = "#58A6FF"
cyan = "#79C0FF"
green = "#3FB950"
red = "#F85149"

[directory]
style = "cyan"

[character]
success_symbol = "[❯](bold purple)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❙](bold blue)"
vimcmd_replace_symbol = "[❯](bold orange)"
vimcmd_replace_one_symbol = "[❯](bold orange)"
vimcmd_visual_symbol = "[❮](bold yellow)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style) "
style = "bold cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
