[mgr]
hovered         = { bg = "#0c0c0c", bold = true }
preview_hovered = { bg = "#0c0c0c", bold = true }
cwd             = { fg = "#79c0ff" }
syntect_theme   = "~/.config/yazi/preview/GitHubDark.tmTheme"

[filetype]
rules = [
  { url = "*/",        fg = "#58a6ff" },
  { url = "*",         is = "link",   fg = "#bc8cff" },
  { url = "*",         is = "orphan", fg = "#ff7b72" },
  { url = "*",         is = "exec",   fg = "#3fb950" },
  { url = "*.zip",     fg = "#f0883e" },
  { url = "*.tar",     fg = "#f0883e" },
  { url = "*.gz",      fg = "#f0883e" },
  { url = "*.7z",      fg = "#f0883e" },
  { mime = "image/*",  fg = "#e3b341" },
  { mime = "video/*",  fg = "#bc8cff" },
  { mime = "audio/*",  fg = "#bc8cff" },
  { url = "*.dmg",     fg = "#e3b341" },
  { url = "*.iso",     fg = "#e3b341" },
  { url = ".*",        fg = "#24282d" },
]

[mode]
normal_main = { bg = "#000000" }
normal_alt  = { bg = "#000000" }

[status]
overall         = { fg = "#24282d", bg = "#000000" }
sep_left        = { open = "", close = "", fg = "#24282d", bg = "#000000" }
sep_right       = { open = "", close = "", fg = "#24282d", bg = "#000000" }
perm_sep        = { fg = "#24282d", bg = "#000000" }
perm_type       = { fg = "#79c0ff",   bg = "#000000" }
perm_read       = { fg = "#e3b341", bg = "#000000" }
perm_write      = { fg = "#ff7b72",    bg = "#000000" }
perm_exec       = { fg = "#3fb950",  bg = "#000000" }
progress_label  = { fg = "#24282d", bg = "#000000" }
progress_normal = { fg = "#24282d", bg = "#000000" }
progress_error  = { fg = "#24282d", bg = "#000000" }
