#!/bin/bash

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh"  # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items"     # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

FONT="JetBrains Mono" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDINGS=3    # All paddings use this value (icon, label, background)

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
cd $HOME/.config/sketchybar/helper && make
$HOME/.config/sketchybar/helper/helper $HELPER >/dev/null 2>&1 &

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist >/dev/null 2>&1 &

# Setting up the general bar appearance of the bar
bar=(
	height=45
	color=$TRANSPARENT
	shadow=off
	position=top
	sticky=off # Must be off unless space switch animations disables (via yabai sip disabled)
	padding_right=10
	padding_left=10
	y_offset=0
	margin=0
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
	updates=when_shown
	icon.font="$FONT:Bold:14.0"
	icon.color=$ICON_COLOR
	icon.padding_left=$PADDINGS
	icon.padding_right=$PADDINGS
	label.font="$FONT:Semibold:13.0"
	label.color=$LABEL_COLOR
	label.padding_left=$PADDINGS
	label.padding_right=$PADDINGS
	padding_right=$PADDINGS
	padding_left=$PADDINGS
	background.height=35
	background.corner_radius=12
	background.border_width=2
	popup.background.border_width=2
	popup.background.corner_radius=9
	popup.background.border_color=$BLACK
	popup.background.color=$BLACK
	popup.blur_radius=20
	popup.background.shadow.drawing=on
)

sketchybar --default "${defaults[@]}"

# Left
source "$ITEM_DIR/spaces.sh"

# Right
source "$ITEM_DIR/front_app.sh"
source "$ITEM_DIR/svim.sh"

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --hotload on
sketchybar --update

echo "sketchybar configuation loaded.."
