#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# If loading the scripting addition fails with an os/kern protection error,
# run: sudo sh "$HOME/.config/yabai/.scripts/patch.sh"
sudo yabai --load-sa

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

# -- Sketchybar events
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

yabai -m config external_bar               all:40:0     \
                mouse_follows_focus        off          \
                focus_follows_mouse        off          \
                display_arrangement_order  default      \
                window_origin_display      default      \
                window_zoom_persist        off          \
                window_placement           second_child \
                window_insertion_point     focused      \
                window_shadow              off          \
                window_opacity             off          \
                window_opacity_duration    0.0          \
                active_window_opacity      1.0          \
                normal_window_opacity      0.90         \
                window_animation_duration  0.0          \
                insert_feedback_color      0xf0000000   \
                split_ratio                0.50         \
                split_type                 auto         \
                auto_balance               off          \
                mouse_modifier             fn           \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                                                        \
                top_padding                10           \
                bottom_padding             10           \
                left_padding               10           \
                right_padding              10           \
                window_gap                 7

# Spaces
yabai -m space 1 --label notes
yabai -m space 2 --label web
yabai -m space 3 --label terminal
yabai -m space 4 --label code
yabai -m space 5 --label other

# Window Rules
yabai -m rule --add app="^Logseq$" space=notes
yabai -m rule --add app="^Zen Browser$" space=web
yabai -m rule --add app="^Ghostty$" space=terminal
yabai -m rule --add app="^Zed$" space=code

# Float Windows
yabai -m rule --add app=Finder manage=off
yabai -m rule --add app="System Settings" manage=off
yabai -m rule --add app=System\ Preferences manage=off
yabai -m rule --add app=Surfshark manage=off
yabai -m rule --add app=Calculator manage=off
yabai -m rule --add app="Alfred Preferences" manage=off

yabai -m config layout bsp

# Start JankyBorders to remove window top shadows
borders active_color=0xf0000000 inactive_color=0xf0000000 width=2.0 hidpi=on style=round

echo "yabai configuration loaded.."
